<?php

/**
 * @file
 * Contains resource_pool.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function resource_pool_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the resource_pool module.
    case 'help.page.resource_pool':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module to help storage those static resource files like image, html.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function resource_pool_theme() {
  $theme = [];
  $theme['base_resource_entity'] = [
    'render element' => 'elements',
    'file' => 'base_resource_entity.page.inc',
    'template' => 'base_resource_entity',
  ];
  $theme['base_resource_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'base_resource_entity.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function resource_pool_theme_suggestions_base_resource_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#base_resource_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'base_resource_entity__' . $sanitized_view_mode;
  $suggestions[] = 'base_resource_entity__' . $entity->bundle();
  $suggestions[] = 'base_resource_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'base_resource_entity__' . $entity->id();
  $suggestions[] = 'base_resource_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
