resource_pool.base_resource_entity_type.*:
  type: config_entity
  label: 'Base Resource Entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string